cluster_name      = "col-corp-eks-test"
aws_region        = "us-east-1"
application_owner = "oosalawu@gmail.com"
application       = "eks-cluster"
environment       = "preprod"
costcenter        = "G001"
